# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_v2_ani_searchuUnwti.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGraphicsView,
    QGroupBox, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QTextBrowser,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1146, 749)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frameSearch = QFrame(self.centralwidget)
        self.frameSearch.setObjectName(u"frameSearch")
        self.frameSearch.setGeometry(QRect(410, 30, 731, 681))
        self.frameSearch.setFrameShape(QFrame.StyledPanel)
        self.frameSearch.setFrameShadow(QFrame.Raised)
        self.groupBox = QGroupBox(self.frameSearch)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 10, 701, 571))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 40, 321, 16))
        self.lineAnimeChoice = QLineEdit(self.groupBox)
        self.lineAnimeChoice.setObjectName(u"lineAnimeChoice")
        self.lineAnimeChoice.setGeometry(QRect(300, 30, 51, 31))
        font = QFont()
        font.setFamilies([u"Academy Engraved LET"])
        font.setPointSize(18)
        self.lineAnimeChoice.setFont(font)
        self.lineAnimeChoice.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)
        self.btnFetchEpisodes = QPushButton(self.groupBox)
        self.btnFetchEpisodes.setObjectName(u"btnFetchEpisodes")
        self.btnFetchEpisodes.setGeometry(QRect(360, 20, 111, 41))
        self.txtBrowserEpisodes = QTextBrowser(self.groupBox)
        self.txtBrowserEpisodes.setObjectName(u"txtBrowserEpisodes")
        self.txtBrowserEpisodes.setGeometry(QRect(10, 60, 251, 291))
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 360, 251, 151))
        self.lineChosenEpisode = QLineEdit(self.groupBox_2)
        self.lineChosenEpisode.setObjectName(u"lineChosenEpisode")
        self.lineChosenEpisode.setGeometry(QRect(70, 50, 111, 31))
        self.lineChosenEpisode.setFont(font)
        self.lineChosenEpisode.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 30, 171, 16))
        self.btnFetchVideo = QPushButton(self.groupBox_2)
        self.btnFetchVideo.setObjectName(u"btnFetchVideo")
        self.btnFetchVideo.setGeometry(QRect(10, 100, 81, 41))
        self.btnSelectAnotherEpisode = QPushButton(self.groupBox_2)
        self.btnSelectAnotherEpisode.setObjectName(u"btnSelectAnotherEpisode")
        self.btnSelectAnotherEpisode.setGeometry(QRect(100, 90, 71, 51))
        self.btnPlayOnMPV = QPushButton(self.groupBox_2)
        self.btnPlayOnMPV.setObjectName(u"btnPlayOnMPV")
        self.btnPlayOnMPV.setGeometry(QRect(180, 100, 61, 41))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 540, 41, 20))
        self.label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineM3u8 = QLineEdit(self.groupBox)
        self.lineM3u8.setObjectName(u"lineM3u8")
        self.lineM3u8.setGeometry(QRect(60, 530, 571, 31))
        self.lineM3u8.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineM3u8.setReadOnly(True)
        self.btnCopy = QPushButton(self.groupBox)
        self.btnCopy.setObjectName(u"btnCopy")
        self.btnCopy.setGeometry(QRect(640, 530, 51, 31))
        self.lblAniTitle = QLabel(self.groupBox)
        self.lblAniTitle.setObjectName(u"lblAniTitle")
        self.lblAniTitle.setGeometry(QRect(270, 70, 271, 31))
        self.lblAniTitle.setFrameShape(QFrame.NoFrame)
        self.txtAniDescription = QTextBrowser(self.groupBox)
        self.txtAniDescription.setObjectName(u"txtAniDescription")
        self.txtAniDescription.setGeometry(QRect(270, 210, 421, 301))
        self.viewAniThumbnail = QGraphicsView(self.groupBox)
        self.viewAniThumbnail.setObjectName(u"viewAniThumbnail")
        self.viewAniThumbnail.setGeometry(QRect(550, 30, 141, 171))
        self.lblMALScore = QLabel(self.groupBox)
        self.lblMALScore.setObjectName(u"lblMALScore")
        self.lblMALScore.setGeometry(QRect(270, 100, 271, 31))
        self.groupBox_3 = QGroupBox(self.frameSearch)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(170, 590, 541, 80))
        self.btnFetchAllVideos = QPushButton(self.groupBox_3)
        self.btnFetchAllVideos.setObjectName(u"btnFetchAllVideos")
        self.btnFetchAllVideos.setGeometry(QRect(10, 20, 141, 51))
        self.lineAllVidsSelection = QLineEdit(self.groupBox_3)
        self.lineAllVidsSelection.setObjectName(u"lineAllVidsSelection")
        self.lineAllVidsSelection.setGeometry(QRect(230, 30, 71, 31))
        self.lineAllVidsSelection.setFont(font)
        self.lineAllVidsSelection.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)
        self.btnPlayVideo = QPushButton(self.groupBox_3)
        self.btnPlayVideo.setObjectName(u"btnPlayVideo")
        self.btnPlayVideo.setGeometry(QRect(310, 20, 141, 51))
        self.btnClose = QPushButton(self.frameSearch)
        self.btnClose.setObjectName(u"btnClose")
        self.btnClose.setGeometry(QRect(30, 600, 121, 71))
        self.grpTrending = QGroupBox(self.centralwidget)
        self.grpTrending.setObjectName(u"grpTrending")
        self.grpTrending.setGeometry(QRect(10, 0, 391, 171))
        self.txtBrowserTrending = QTextBrowser(self.grpTrending)
        self.txtBrowserTrending.setObjectName(u"txtBrowserTrending")
        self.txtBrowserTrending.setGeometry(QRect(10, 20, 371, 141))
        self.grpPopular = QGroupBox(self.centralwidget)
        self.grpPopular.setObjectName(u"grpPopular")
        self.grpPopular.setGeometry(QRect(10, 180, 391, 171))
        self.txtBrowserPopular = QTextBrowser(self.grpPopular)
        self.txtBrowserPopular.setObjectName(u"txtBrowserPopular")
        self.txtBrowserPopular.setGeometry(QRect(10, 20, 371, 141))
        self.chkDub = QCheckBox(self.centralwidget)
        self.chkDub.setObjectName(u"chkDub")
        self.chkDub.setGeometry(QRect(200, 410, 51, 21))
        self.lineSearch = QLineEdit(self.centralwidget)
        self.lineSearch.setObjectName(u"lineSearch")
        self.lineSearch.setGeometry(QRect(90, 370, 211, 31))
        font1 = QFont()
        font1.setFamilies([u"Arial Black"])
        font1.setPointSize(15)
        font1.setBold(False)
        font1.setItalic(False)
        self.lineSearch.setFont(font1)
        self.lineSearch.setAlignment(Qt.AlignCenter)
        self.chkSub = QCheckBox(self.centralwidget)
        self.chkSub.setObjectName(u"chkSub")
        self.chkSub.setGeometry(QRect(130, 410, 51, 21))
        self.btnSearch = QPushButton(self.centralwidget)
        self.btnSearch.setObjectName(u"btnSearch")
        self.btnSearch.setGeometry(QRect(310, 370, 81, 31))
        self.lblSearch = QLabel(self.centralwidget)
        self.lblSearch.setObjectName(u"lblSearch")
        self.lblSearch.setGeometry(QRect(20, 370, 71, 31))
        font2 = QFont()
        font2.setFamilies([u"Fira Sans"])
        font2.setPointSize(15)
        self.lblSearch.setFont(font2)
        self.grpSearchResults = QGroupBox(self.centralwidget)
        self.grpSearchResults.setObjectName(u"grpSearchResults")
        self.grpSearchResults.setGeometry(QRect(10, 430, 381, 281))
        self.txtBrowserSearchResult = QTextBrowser(self.grpSearchResults)
        self.txtBrowserSearchResult.setObjectName(u"txtBrowserSearchResult")
        self.txtBrowserSearchResult.setGeometry(QRect(10, 30, 361, 231))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Anime Selection", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Your Anime Choice (Episode index number ex. 3", None))
        self.lineAnimeChoice.setText("")
        self.btnFetchEpisodes.setText(QCoreApplication.translate("MainWindow", u"Fetch Episodes", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Single Episode Selection", None))
        self.lineChosenEpisode.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Enter Your Chosen Episode:", None))
        self.btnFetchVideo.setText(QCoreApplication.translate("MainWindow", u"Fetch Video", None))
        self.btnSelectAnotherEpisode.setText(QCoreApplication.translate("MainWindow", u"Another\n"
"Episode?", None))
        self.btnPlayOnMPV.setText(QCoreApplication.translate("MainWindow", u"MPV", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"M3U8:", None))
        self.lineM3u8.setText("")
        self.btnCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.lblAniTitle.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lblMALScore.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Crawler", None))
        self.btnFetchAllVideos.setText(QCoreApplication.translate("MainWindow", u"Fetch All Videos", None))
        self.lineAllVidsSelection.setText("")
        self.btnPlayVideo.setText(QCoreApplication.translate("MainWindow", u"Play Selection", None))
        self.btnClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.grpTrending.setTitle(QCoreApplication.translate("MainWindow", u"Trending", None))
        self.grpPopular.setTitle(QCoreApplication.translate("MainWindow", u"Popular", None))
        self.chkDub.setText(QCoreApplication.translate("MainWindow", u"Dub", None))
        self.lineSearch.setText("")
        self.chkSub.setText(QCoreApplication.translate("MainWindow", u"Sub", None))
        self.btnSearch.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.lblSearch.setText(QCoreApplication.translate("MainWindow", u"Search:", None))
        self.grpSearchResults.setTitle(QCoreApplication.translate("MainWindow", u"Search Results", None))
    # retranslateUi

