# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'v2_ani_searchoFaVNl.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QStatusBar, QTextBrowser, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(895, 682)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frameSearch = QFrame(self.centralwidget)
        self.frameSearch.setObjectName(u"frameSearch")
        self.frameSearch.setGeometry(QRect(10, 190, 871, 61))
        self.frameSearch.setFrameShape(QFrame.StyledPanel)
        self.frameSearch.setFrameShadow(QFrame.Raised)
        self.lblSearch = QLabel(self.frameSearch)
        self.lblSearch.setObjectName(u"lblSearch")
        self.lblSearch.setGeometry(QRect(10, 10, 111, 51))
        font = QFont()
        font.setFamilies([u"Academy Engraved LET"])
        font.setPointSize(18)
        self.lblSearch.setFont(font)
        self.btnSearch = QPushButton(self.frameSearch)
        self.btnSearch.setObjectName(u"btnSearch")
        self.btnSearch.setGeometry(QRect(680, 10, 91, 41))
        self.chkSub = QCheckBox(self.frameSearch)
        self.chkSub.setObjectName(u"chkSub")
        self.chkSub.setGeometry(QRect(790, 10, 51, 21))
        self.chkDub = QCheckBox(self.frameSearch)
        self.chkDub.setObjectName(u"chkDub")
        self.chkDub.setGeometry(QRect(790, 30, 51, 21))
        self.lineSearch = QLineEdit(self.frameSearch)
        self.lineSearch.setObjectName(u"lineSearch")
        self.lineSearch.setGeometry(QRect(130, 10, 521, 41))
        font1 = QFont()
        font1.setFamilies([u"Arial Black"])
        font1.setPointSize(18)
        font1.setBold(True)
        font1.setItalic(False)
        self.lineSearch.setFont(font1)
        self.lineSearch.setAlignment(Qt.AlignCenter)
        self.grpSearchResults = QGroupBox(self.centralwidget)
        self.grpSearchResults.setObjectName(u"grpSearchResults")
        self.grpSearchResults.setGeometry(QRect(10, 260, 321, 281))
        self.txtBrowserSearchResult = QTextBrowser(self.grpSearchResults)
        self.txtBrowserSearchResult.setObjectName(u"txtBrowserSearchResult")
        self.txtBrowserSearchResult.setGeometry(QRect(10, 30, 301, 241))
        self.grpTrending = QGroupBox(self.centralwidget)
        self.grpTrending.setObjectName(u"grpTrending")
        self.grpTrending.setGeometry(QRect(10, 10, 391, 171))
        self.txtBrowserTrending = QTextBrowser(self.grpTrending)
        self.txtBrowserTrending.setObjectName(u"txtBrowserTrending")
        self.txtBrowserTrending.setGeometry(QRect(10, 20, 371, 141))
        self.grpPopular = QGroupBox(self.centralwidget)
        self.grpPopular.setObjectName(u"grpPopular")
        self.grpPopular.setGeometry(QRect(470, 10, 391, 171))
        self.txtBrowserPopular = QTextBrowser(self.grpPopular)
        self.txtBrowserPopular.setObjectName(u"txtBrowserPopular")
        self.txtBrowserPopular.setGeometry(QRect(10, 20, 371, 141))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(340, 260, 541, 301))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 40, 321, 16))
        self.lineAnimeChoice = QLineEdit(self.groupBox)
        self.lineAnimeChoice.setObjectName(u"lineAnimeChoice")
        self.lineAnimeChoice.setGeometry(QRect(300, 30, 51, 31))
        self.lineAnimeChoice.setFont(font)
        self.lineAnimeChoice.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)
        self.btnFetchEpisodes = QPushButton(self.groupBox)
        self.btnFetchEpisodes.setObjectName(u"btnFetchEpisodes")
        self.btnFetchEpisodes.setGeometry(QRect(360, 20, 111, 41))
        self.txtBrowserEpisodes = QTextBrowser(self.groupBox)
        self.txtBrowserEpisodes.setObjectName(u"txtBrowserEpisodes")
        self.txtBrowserEpisodes.setGeometry(QRect(10, 70, 251, 181))
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(270, 70, 261, 181))
        self.lineChosenEpisode = QLineEdit(self.groupBox_2)
        self.lineChosenEpisode.setObjectName(u"lineChosenEpisode")
        self.lineChosenEpisode.setGeometry(QRect(80, 50, 111, 31))
        self.lineChosenEpisode.setFont(font)
        self.lineChosenEpisode.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 30, 171, 16))
        self.btnFetchVideo = QPushButton(self.groupBox_2)
        self.btnFetchVideo.setObjectName(u"btnFetchVideo")
        self.btnFetchVideo.setGeometry(QRect(10, 90, 81, 81))
        self.btnSelectAnotherEpisode = QPushButton(self.groupBox_2)
        self.btnSelectAnotherEpisode.setObjectName(u"btnSelectAnotherEpisode")
        self.btnSelectAnotherEpisode.setGeometry(QRect(100, 90, 81, 81))
        self.btnPlayOnMPV = QPushButton(self.groupBox_2)
        self.btnPlayOnMPV.setObjectName(u"btnPlayOnMPV")
        self.btnPlayOnMPV.setGeometry(QRect(190, 90, 61, 81))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 270, 41, 20))
        self.label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineM3u8 = QLineEdit(self.groupBox)
        self.lineM3u8.setObjectName(u"lineM3u8")
        self.lineM3u8.setGeometry(QRect(60, 260, 411, 31))
        self.lineM3u8.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineM3u8.setReadOnly(True)
        self.btnCopy = QPushButton(self.groupBox)
        self.btnCopy.setObjectName(u"btnCopy")
        self.btnCopy.setGeometry(QRect(480, 260, 51, 41))
        self.btnClose = QPushButton(self.centralwidget)
        self.btnClose.setObjectName(u"btnClose")
        self.btnClose.setGeometry(QRect(100, 560, 121, 71))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(340, 560, 541, 80))
        self.btnFetchAllVideos = QPushButton(self.groupBox_3)
        self.btnFetchAllVideos.setObjectName(u"btnFetchAllVideos")
        self.btnFetchAllVideos.setGeometry(QRect(10, 20, 141, 51))
        self.lineAllVidsSelection = QLineEdit(self.groupBox_3)
        self.lineAllVidsSelection.setObjectName(u"lineAllVidsSelection")
        self.lineAllVidsSelection.setGeometry(QRect(230, 30, 71, 31))
        self.lineAllVidsSelection.setFont(font)
        self.lineAllVidsSelection.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)
        self.btnPlayVideo = QPushButton(self.groupBox_3)
        self.btnPlayVideo.setObjectName(u"btnPlayVideo")
        self.btnPlayVideo.setGeometry(QRect(310, 20, 141, 51))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.lblSearch.setText(QCoreApplication.translate("MainWindow", u"Search Anime:", None))
        self.btnSearch.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.chkSub.setText(QCoreApplication.translate("MainWindow", u"Sub", None))
        self.chkDub.setText(QCoreApplication.translate("MainWindow", u"Dub", None))
        self.lineSearch.setText("")
        self.grpSearchResults.setTitle(QCoreApplication.translate("MainWindow", u"Search Results", None))
        self.grpTrending.setTitle(QCoreApplication.translate("MainWindow", u"Trending", None))
        self.grpPopular.setTitle(QCoreApplication.translate("MainWindow", u"Popular", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Anime Selection", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Your Anime Choice (Episode index number ex. 3", None))
        self.lineAnimeChoice.setText("")
        self.btnFetchEpisodes.setText(QCoreApplication.translate("MainWindow", u"Fetch Episodes", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Single Episode Selection", None))
        self.lineChosenEpisode.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Enter Your Chosen Episode:", None))
        self.btnFetchVideo.setText(QCoreApplication.translate("MainWindow", u"Fetch Video", None))
        self.btnSelectAnotherEpisode.setText(QCoreApplication.translate("MainWindow", u"Select \n"
"Another \n"
"Episode", None))
        self.btnPlayOnMPV.setText(QCoreApplication.translate("MainWindow", u"MPV", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"M3U8:", None))
        self.lineM3u8.setText("")
        self.btnCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.btnClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Crawler", None))
        self.btnFetchAllVideos.setText(QCoreApplication.translate("MainWindow", u"Fetch All Videos", None))
        self.lineAllVidsSelection.setText("")
        self.btnPlayVideo.setText(QCoreApplication.translate("MainWindow", u"Play Selection", None))
    # retranslateUi

